default_language_version:
  python: python3.11

repos:
  # This checks any wrong json schema
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.4
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]

  # This checks for any potential detecting and preventing hardcoded secrets like
  # passwords, API keys, and tokens in git repos. Gitleaks is an easy-to-use, all-in-one
  # solution for detecting secrets, past or present, in your code.
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.14.1
    hooks:
      - id: gitleaks

  # TODO: Move this to CI
  # Reorder imports
  # - repo: https://github.com/asottile/reorder_python_imports
  #   rev: v3.9.0
  #   hooks:
  #     - id: reorder-python-imports
  #       args: ["--py311-plus", "--application-directories=src/"]
  #       # need to ignore alembic files, since reorder-python-imports gets confused
  #       # and thinks that alembic is a local package since there is a folder
  #       # in the backend directory called `alembic`
  #       exclude: ^src/deprecated_scripts/

  # INFO: Deprecated, using ruff-format
  # Formatter
  # - repo: https://github.com/psf/black
  #   rev: 24.10.0
  #   hooks:
  #     - id: black
  #       language_version: python3.11
  #       args: [--extend-exclude, "src/rules/structures/__init__.py"]

  # TODO: Move this to CI
  # The repo currently does not and should not have imports with side effects
  # These settings will remove unused imports with side effects
  # - repo: https://github.com/PyCQA/autoflake
  #   rev: v2.2.0
  #   hooks:
  #     - id: autoflake
  #       args:
  #         [
  #           "--remove-all-unused-imports",
  #           "--remove-unused-variables",
  #           "--in-place",
  #           "--recursive",
  #         ]

  # TODO: Move this to CI in the future
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
      - id: ruff-format
