default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        name: Check commit message naming convention
        stages: [commit-msg]
        args: [--verbose] # Optional: specify allowed commit types, e.g., [feat, fix, ci, chore, test]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Check for trailing whitespace
      - id: check-json
        name: Check JSON
      - id: check-yaml
        name: Check YAML
        args: [--unsafe]
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: detect-private-key
        name: Detect Private Key

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["--skip", "node_modules,dist"] # Exclude folders if needed
        files: "\\.(py|js|ts)$" # Regex to match Python, JavaScript, and TypeScript files

  # This checks any wrong json schema
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.4
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]

  # This checks for any potential detecting and preventing hardcoded secrets like
  # passwords, API keys, and tokens in git repos. Gitleaks is an easy-to-use, all-in-one
  # solution for detecting secrets, past or present, in your code.
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.14.1
    hooks:
      - id: gitleaks

  # Reorder python imports
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.14.0
    hooks:
      - id: reorder-python-imports
        args: [
            "--application-directories=backend",
            "--unclassifiable-application-module=app", # app is the main module
            "--py311-plus",
          ]
        # need to ignore alembic files, since reorder-python-imports gets confused
        # and thinks that alembic is a local package since there is a folder
        # in the backend directory called `alembic`
        exclude: ^backend/alembic

  # The repo currently does not and should not have imports with side effects
  # These settings will remove unused imports with side effects
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [
            "-r", # recursive
            "--remove-all-unused-imports",
            "--ignore-init-module-imports",
            "--remove-unused-variables",
            "--verbose",
            "--in-place",
          ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      # Run the ruff linter
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
      # Run the ruff formatter
      - id: ruff-format
        types_or: [python, pyi]

  # INFO: wait for frontend to be ready
  # This checks for any potential detecting and preventing hardcoded secrets like
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.1.0
  #   hooks:
  #     - id: prettier
  #       types_or: [html, css, javascript, ts, tsx]
  #       additional_dependencies:
  #         - prettier
