"""add foreign from chat_session to folder

Revision ID: 36e9e94abfc0
Revises: 637ab9958b11
Create Date: 2025-01-07 13:51:24.137077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = "36e9e94abfc0"
down_revision: Union[str, None] = "637ab9958b11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_session", sa.Column("folder_id", mssql.UNIQUEIDENTIFIER(), nullable=True))
    op.create_foreign_key(
        "FK__chat_session__folder", "chat_session", "folder", ["folder_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("FK__chat_session__folder", "chat_session", type_="foreignkey")
    op.drop_column("chat_session", "folder_id")
    # ### end Alembic commands ###
