"""add foreign from chat_session to user

Revision ID: 3ddac298fb73
Revises: 5a6605ebe3c9
Create Date: 2025-01-07 14:08:57.898210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = "3ddac298fb73"
down_revision: Union[str, None] = "5a6605ebe3c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_session", sa.Column("user_id", mssql.UNIQUEIDENTIFIER(), nullable=False))
    op.create_foreign_key(None, "chat_session", "user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat_session", type_="foreignkey")
    op.drop_column("chat_session", "user_id")
    # ### end Alembic commands ###
