"""add foreign from folder to user

Revision ID: 5a6605ebe3c9
Revises: 6e3de72aa2c0
Create Date: 2025-01-07 14:07:54.648648

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = "5a6605ebe3c9"
down_revision: Union[str, None] = "6e3de72aa2c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("folder", sa.Column("user_id", mssql.UNIQUEIDENTIFIER(), nullable=False))
    op.create_foreign_key(
        "FK__folder__user", "folder", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("FK__folder__user", "folder", type_="foreignkey")
    op.drop_column("folder", "user_id")
    # ### end Alembic commands ###
