"""add columns in table user with schema: email, name, avatar, hashed_password, role, is_oauth

Revision ID: 5da9aba17cb5
Revises: cb1bf6e87a3e
Create Date: 2025-01-07 17:09:19.346359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5da9aba17cb5"
down_revision: Union[str, None] = "cb1bf6e87a3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.String(), nullable=False))
    op.add_column("user", sa.Column("name", sa.String(), nullable=True))
    op.add_column("user", sa.Column("avatar", sa.String(), nullable=True))
    op.add_column("user", sa.Column("hashed_password", sa.String(), nullable=True))
    op.add_column(
        "user",
        sa.Column(
            "role", sa.Enum("ADMIN", "BASIC", name="userrole", native_enum=False), nullable=False
        ),
    )
    op.add_column("user", sa.Column("is_oauth", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_oauth")
    op.drop_column("user", "role")
    op.drop_column("user", "hashed_password")
    op.drop_column("user", "avatar")
    op.drop_column("user", "name")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
