"""add table chat_message

Revision ID: 637ab9958b11
Revises: f7c3dc060944
Create Date: 2025-01-07 13:50:02.132695

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = "637ab9958b11"
down_revision: Union[str, None] = "f7c3dc060944"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_message",
        sa.Column("id", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("parent_message_id", mssql.UNIQUEIDENTIFIER(), nullable=True),
        sa.Column("child_message_id", mssql.UNIQUEIDENTIFIER(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "message_type",
            sa.Enum("SYSTEM", "USER", "ASSISTANT", name="chatmessagetype", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "error_type",
            sa.Enum(
                "SYSTEM_ERROR",
                "VALIDATION_ERROR",
                "NETWORK_ERROR",
                "GENERATION_ERROR",
                name="chatmessageerrortype",
            ),
            nullable=True,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_message_id"],
            ["chat_message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_message_id"],
            ["chat_message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_message")
    # ### end Alembic commands ###
