"""add foreign from agent to user

Revision ID: 6e3de72aa2c0
Revises: d09ec0a7b6af
Create Date: 2025-01-07 14:06:19.784283

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = "6e3de72aa2c0"
down_revision: Union[str, None] = "d09ec0a7b6af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent", sa.Column("user_id", mssql.UNIQUEIDENTIFIER(), nullable=True))
    op.create_foreign_key(None, "agent", "user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "agent", type_="foreignkey")
    op.drop_column("agent", "user_id")
    # ### end Alembic commands ###
