"""modify column type for handling storing vietnamese text

Revision ID: 75df014606e4
Revises: 4dd998601576
Create Date: 2025-01-25 15:11:45.146000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75df014606e4"
down_revision: Union[str, None] = "4dd998601576"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("data_docstore_idx_key_namespace", table_name="data_docstore")
    op.drop_table("data_docstore")
    op.alter_column(
        "chat_message",
        "message",
        existing_type=sa.NVARCHAR(length=4000, collation="SQL_Latin1_General_CP1_CI_AS"),
        type_=sa.NVARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_message",
        "message",
        existing_type=sa.NVARCHAR(),
        type_=sa.NVARCHAR(length=4000, collation="SQL_Latin1_General_CP1_CI_AS"),
        nullable=True,
    )
    op.create_table(
        "data_docstore",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(always=False, start=1, increment=1),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "key",
            sa.NVARCHAR(length=255, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "namespace",
            sa.NVARCHAR(length=255, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "value",
            sa.NVARCHAR(collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="PK__data_doc__3213E83FA3849565"),
    )
    op.create_index(
        "data_docstore_idx_key_namespace", "data_docstore", ["key", "namespace"], unique=False
    )
    # ### end Alembic commands ###
