"""remove unused column link in document metadata table

Revision ID: 89fb492b1e99
Revises: a2b035522b2d
Create Date: 2025-01-15 10:42:26.048739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89fb492b1e99"
down_revision: Union[str, None] = "a2b035522b2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_metadata", "link")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_metadata",
        sa.Column(
            "link",
            sa.VARCHAR(collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
