"""remove column display_priority in table folder

Revision ID: 989953ae75e5
Revises: 5da9aba17cb5
Create Date: 2025-01-09 13:11:21.102179

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "989953ae75e5"
down_revision: Union[str, None] = "5da9aba17cb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("folder", "display_priority")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "folder", sa.Column("display_priority", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
