"""remove self-foreign keys in table chat_message

Revision ID: afc5e773d532
Revises: c48653da954b
Create Date: 2025-02-01 04:46:04.348837

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "afc5e773d532"
down_revision: Union[str, None] = "c48653da954b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("FK__chat_mess__paren__3F466844", "chat_message", type_="foreignkey")
    op.drop_constraint("FK__chat_mess__child__3E52440B", "chat_message", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "FK__chat_mess__child__3E52440B",
        "chat_message",
        "chat_message",
        ["child_message_id"],
        ["id"],
    )
    op.create_foreign_key(
        "FK__chat_mess__paren__3F466844",
        "chat_message",
        "chat_message",
        ["parent_message_id"],
        ["id"],
    )
    # ### end Alembic commands ###
