"""add foreign from chat_message to chat_session

Revision ID: c2dc180ed8a7
Revises: 36e9e94abfc0
Create Date: 2025-01-07 13:52:53.872020

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = "c2dc180ed8a7"
down_revision: Union[str, None] = "36e9e94abfc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_message", sa.Column("chat_session_id", mssql.UNIQUEIDENTIFIER(), nullable=False)
    )
    op.create_foreign_key(
        None, "chat_message", "chat_session", ["chat_session_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat_message", type_="foreignkey")
    op.drop_column("chat_message", "chat_session_id")
    # ### end Alembic commands ###
