"""modify column description of table chat session for handling storing vietnamese text

Revision ID: c48653da954b
Revises: 4dd998601576
Create Date: 2025-01-25 15:19:15.061292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c48653da954b"
down_revision: Union[str, None] = "4dd998601576"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_session",
        "description",
        existing_type=sa.VARCHAR(length=255, collation="SQL_Latin1_General_CP1_CI_AS"),
        type_=sa.NVARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_session",
        "description",
        existing_type=sa.NVARCHAR(),
        type_=sa.VARCHAR(length=255, collation="SQL_Latin1_General_CP1_CI_AS"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
