"""modify column name of table user for handling storing vietnamese text

Revision ID: cc08b43d91ed
Revises: c48653da954b
Create Date: 2025-01-25 15:24:43.797673

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "cc08b43d91ed"
down_revision: Union[str, None] = "c48653da954b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
