"""add foreign from chat_session to agent

Revision ID: e16788f843d0
Revises: cfb28202c9f8
Create Date: 2025-01-07 13:59:37.628567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = "e16788f843d0"
down_revision: Union[str, None] = "cfb28202c9f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_session", sa.Column("agent_id", mssql.UNIQUEIDENTIFIER(), nullable=True))
    op.create_foreign_key(None, "chat_session", "agent", ["agent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat_session", type_="foreignkey")
    op.drop_column("chat_session", "agent_id")
    # ### end Alembic commands ###
