from enum import Enum

class ErrorCodes(Enum):
    # Auth errors
    OAUTH_LOGIN_FAILED = (400, "OAUTH_LOGIN_FAILED")
    TOKEN_INVALID = (400, "TOKEN_INVALID")
    AUTHENTICATION_FAILED = (401, "AUTHENTICATION_FAILED")
    UNAUTHORIZED_REQUEST = (401, "UNAUTHORIZED_REQUEST")
    TOKEN_EXPIRED = (401, "TOKEN_EXPIRED")
    REFRESH_TOKEN_EXPIRED = (401, "REFRESH_TOKEN_EXPIRED")
    ACCESS_DENIED = (403, "ACCESS_DENIED")
    PERMISSION_DENIED = (403, "PERMISSION_DENIED")
    USER_NOT_FOUND = (404, "USER_NOT_FOUND")
    USER_ALREADY_EXISTS = (409, "USER_ALREADY_EXISTS")

    # Request errors
    BAD_REQUEST = (400, "BAD_REQUEST")
    INVALID_REQUEST = (400, "INVALID_REQUEST")
    INVALID_QUERY_PARAMETER = (400, "INVALID_QUERY_PARAMETER")
    FORBIDDEN_REQUEST = (403, "FORBIDDEN_REQUEST")
    NOT_FOUND = (404, "NOT_FOUND")
    REQUEST_TIMEOUT = (408, "REQUEST_TIMEOUT")
    DUPLICATE_REQUEST = (409, "DUPLICATE_REQUEST")
    NOT_ACCEPTABLE = (409, "NOT_ACCEPTABLE")
    PAYLOAD_TOO_LARGE = (413, "PAYLOAD_TOO_LARGE")
    UNSUPPORTED_MEDIA_TYPE = (415, "UNSUPPORTED_MEDIA_TYPE")
    RANGE_NOT_SATISFIABLE = (416, "RANGE_NOT_SATISFIABLE")
    TOO_MANY_REQUESTS = (429, "TOO_MANY_REQUESTS")

    # Database errors
    DB_OPERATIONAL_ERROR = (500, "DB_OPERATION_FAILED")
    DB_DEADLOCK_ERROR = (500, "DB_DEADLOCK_DETECTED")

    # MSSQL errors
    MSSQL_OPERATIONAL_ERROR = (500, "MSSQL_OPERATION_FAILED")
    MSSQL_QUERY_ERROR = (500, "MSSQL_QUERY_FAILED")

    # Redis errors
    REDIS_KEY_NOT_FOUND = (404, "REDIS_KEY_NOT_FOUND")
    REDIS_CONNECTION_ERROR = (500, "REDIS_CONNECTION_FAILED")
    REDIS_TIMEOUT_ERROR = (504, "REDIS_TIMEOUT")

    # MinIO errors
    MINIO_BUCKET_NOT_FOUND = (404, "MINIO_BUCKET_NOT_FOUND")
    MINIO_CONNECTION_ERROR = (500, "MINIO_CONNECTION_FAILED")
    MINIO_UPLOAD_ERROR = (500, "MINIO_UPLOAD_FAILED")
    MINIO_DOWNLOAD_ERROR = (500, "MINIO_DOWNLOAD_FAILED")

    # Chatbot errors
    CHAT_SESSION_NOT_FOUND = (404, "CHAT_SESSION_NOT_FOUND")
    CHAT_MESSAGE_NOT_FOUND = (404, "CHAT_MESSAGE_NOT_FOUND")
    LLM_PROVIDER_NOT_FOUND = (404, "LLM_PROVIDER_NOT_FOUND")
    EMBEDDING_PROVIDER_NOT_FOUND = (404, "EMBEDDING_PROVIDER_NOT_FOUND")
    PROVIDER_TYPE_CHANGE_NOT_ALLOWED = (422, "PROVIDER_TYPE_CHANGE_NOT_ALLOWED")

    # Server errors
    INTERNAL_SERVER_ERROR = (500, "INTERNAL_SERVER_ERROR")
    BAD_GATEWAY = (502, "BAD_GATEWAY")
    SERVICE_UNAVAILABLE = (503, "SERVICE_UNAVAILABLE")
    GATEWAY_TIMEOUT = (504, "GATEWAY_TIMEOUT")

    def status_code(self):
        return self.value[0]

    def message(self):
        return self.value[1]