export const CHATBOT_CORE_BACKEND_URL = process.env.NEXT_PUBLIC_CHATBOT_CORE_BACKEND_URL!;
export const API_VERSION = process.env.NEXT_PUBLIC_API_VERSION!;

export const LODASH_DEBOUNCE_TIME_MILLISECONDS = 275;
