export const CHATBOT_CORE_BACKEND_URL = process.env.NEXT_PUBLIC_CHATBOT_CORE_BACKEND_URL!;
export const API_VERSION = process.env.NEXT_PUBLIC_API_VERSION!;

export const LODASH_DEBOUNCE_TIME_MILLISECONDS = 275;

export const LOCAL_STORAGE_ACCESS_TOKEN_KEY = process.env.NEXT_PUBLIC_LOCAL_STORAGE_KEY_ACCESS_TOKEN!;

export const CLIENT_DOMAIN = process.env.NEXT_PUBLIC_CLIENT_DOMAIN!;
