from enum import Enum

from settings import Constants


class ErrorCodesMappingNumber(Enum):

    INVALID_REQUEST = (400, Constants.INVALID_REQUEST_MESSAGE)
    UNAUTHORIZED_REQUEST = (401, Constants.UNAUTHORIZED_REQUEST_MESSAGE)
    FORBIDDEN_REQUEST = (403, Constants.FORBIDDEN_REQUEST_MESSAGE)
    NOT_FOUND = (404, Constants.NOT_FOUND_MESSAGE)
    INTERNAL_SERVER_ERROR = (500, Constants.INTERNAL_SERVER_ERROR_MESSAGE)
