"""modify column primary_owners to be nullable

Revision ID: 4dd998601576
Revises: dc5a2749e3af
Create Date: 2025-01-15 10:46:06.211465

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4dd998601576"
down_revision: Union[str, None] = "dc5a2749e3af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_metadata",
        "primary_owners",
        existing_type=sa.VARCHAR(collation="SQL_Latin1_General_CP1_CI_AS"),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_metadata",
        "primary_owners",
        existing_type=sa.VARCHAR(collation="SQL_Latin1_General_CP1_CI_AS"),
        nullable=False,
    )
    # ### end Alembic commands ###
