"""add table llm_provider

Revision ID: 71a88f740b61
Revises: 0e8338e6a569
Create Date: 2025-01-07 13:39:03.704354

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = "71a88f740b61"
down_revision: Union[str, None] = "0e8338e6a569"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_provider",
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("id", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column(
            "name",
            sa.Enum("OPENAI", "GEMINI", "COHERE", name="providertype", native_enum=False),
            nullable=False,
        ),
        sa.Column("api_key", sa.LargeBinary(), nullable=True),
        sa.Column("models", sa.String(), nullable=True),
        sa.Column("current_model", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_default_provider", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_provider")
    # ### end Alembic commands ###
