"""modify column last_synced_at to nullable

Revision ID: dc5a2749e3af
Revises: 89fb492b1e99
Create Date: 2025-01-15 10:44:50.506593

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = "dc5a2749e3af"
down_revision: Union[str, None] = "89fb492b1e99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_metadata", "last_synced_at", existing_type=mssql.DATETIMEOFFSET(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_metadata", "last_synced_at", existing_type=mssql.DATETIMEOFFSET(), nullable=False
    )
    # ### end Alembic commands ###
