import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "chatbot-api/sample-backend",
    },
    {
      type: "category",
      label: "auth",
      items: [
        {
          type: "doc",
          id: "chatbot-api/oauth-google-database-authorize-auth-oauth-authorize-get",
          label: "Oauth:Google.Database.Authorize",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/oauth-google-database-callback-auth-oauth-callback-get",
          label: "Oauth:Google.Database.Callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/auth-database-logout-auth-logout-post",
          label: "Auth:Database.Logout",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "UNTAGGED",
      items: [
        {
          type: "doc",
          id: "chatbot-api/get-user-chat-sessions-chat-get-user-chat-sessions-get",
          label: "Get User Chat Sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-chat-session-chat-get-chat-session-session-id-get",
          label: "Get Chat Session",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/create-new-chat-session-chat-create-chat-session-post",
          label: "Create New Chat Session",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/rename-chat-session-chat-rename-chat-session-put",
          label: "Rename Chat Session",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-chat-session-by-id-chat-delete-chat-session-session-id-delete",
          label: "Delete Chat Session By Id",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/handle-new-chat-message-chat-send-message-post",
          label: "Handle New Chat Message",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/set-message-as-latest-chat-set-message-as-latest-put",
          label: "Set Message As Latest",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "chatbot-api/create-chat-feedback-chat-create-chat-message-feedback-post",
          label: "Create Chat Feedback",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/create-search-feedback-chat-document-search-feedback-post",
          label: "Create Search Feedback",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/get-max-document-tokens-chat-max-selected-document-tokens-get",
          label: "Get Max Document Tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-tags-query-valid-tags-get",
          label: "Get Tags",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-search-type-query-search-intent-post",
          label: "Get Search Type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/query-validation-query-query-validation-post",
          label: "Query Validation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/stream-query-validation-query-stream-query-validation-post",
          label: "Stream Query Validation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/get-answer-with-quote-query-stream-answer-with-quote-post",
          label: "Get Answer With Quote",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/get-document-info-document-document-size-info-get",
          label: "Get Document Info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-chunk-info-document-chunk-info-get",
          label: "Get Chunk Info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/admin-search-admin-search-post",
          label: "Admin Search",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/get-most-boosted-docs-manage-admin-doc-boosts-get",
          label: "Get Most Boosted Docs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/document-boost-update-manage-admin-doc-boosts-post",
          label: "Document Boost Update",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/document-hidden-update-manage-admin-doc-hidden-post",
          label: "Document Hidden Update",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/validate-existing-genai-api-key-manage-admin-genai-api-key-validate-get",
          label: "Validate Existing Genai Api Key",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-gen-ai-api-key-from-dynamic-config-store-manage-admin-genai-api-key-get",
          label: "Get Gen Ai Api Key From Dynamic Config Store",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/store-genai-api-key-manage-admin-genai-api-key-put",
          label: "Store Genai Api Key",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-genai-api-key-manage-admin-genai-api-key-delete",
          label: "Delete Genai Api Key",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/create-deletion-attempt-for-connector-id-manage-admin-deletion-attempt-post",
          label: "Create Deletion Attempt For Connector Id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/promote-admin-manage-promote-user-to-admin-patch",
          label: "Promote Admin",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "chatbot-api/list-all-users-manage-users-get",
          label: "List All Users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-user-role-manage-get-user-role-get",
          label: "Get User Role",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/verify-user-logged-in-manage-me-get",
          label: "Verify User Logged In",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/check-google-app-gmail-credentials-exist-manage-admin-connector-gmail-app-credential-get",
          label: "Check Google App Gmail Credentials Exist",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/upsert-google-app-gmail-credentials-manage-admin-connector-gmail-app-credential-put",
          label: "Upsert Google App Gmail Credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-google-app-gmail-credentials-manage-admin-connector-gmail-app-credential-delete",
          label: "Delete Google App Gmail Credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/check-google-app-credentials-exist-manage-admin-connector-google-drive-app-credential-get",
          label: "Check Google App Credentials Exist",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/upsert-google-app-credentials-manage-admin-connector-google-drive-app-credential-put",
          label: "Upsert Google App Credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-google-app-credentials-manage-admin-connector-google-drive-app-credential-delete",
          label: "Delete Google App Credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/check-google-service-gmail-account-key-exist-manage-admin-connector-gmail-service-account-key-get",
          label: "Check Google Service Gmail Account Key Exist",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/upsert-google-service-gmail-account-key-manage-admin-connector-gmail-service-account-key-put",
          label: "Upsert Google Service Gmail Account Key",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-google-service-gmail-account-key-manage-admin-connector-gmail-service-account-key-delete",
          label: "Delete Google Service Gmail Account Key",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/check-google-service-account-key-exist-manage-admin-connector-google-drive-service-account-key-get",
          label: "Check Google Service Account Key Exist",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/upsert-google-service-account-key-manage-admin-connector-google-drive-service-account-key-put",
          label: "Upsert Google Service Account Key",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-google-service-account-key-manage-admin-connector-google-drive-service-account-key-delete",
          label: "Delete Google Service Account Key",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/upsert-service-account-credential-manage-admin-connector-google-drive-service-account-credential-put",
          label: "Upsert Service Account Credential",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "chatbot-api/upsert-gmail-service-account-credential-manage-admin-connector-gmail-service-account-credential-put",
          label: "Upsert Gmail Service Account Credential",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "chatbot-api/check-drive-tokens-manage-admin-connector-google-drive-check-auth-credential-id-get",
          label: "Check Drive Tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/admin-google-drive-auth-manage-admin-connector-google-drive-authorize-credential-id-get",
          label: "Admin Google Drive Auth",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/upload-files-manage-admin-connector-file-upload-post",
          label: "Upload Files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/get-connector-indexing-status-manage-admin-connector-indexing-status-get",
          label: "Get Connector Indexing Status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/create-connector-from-model-manage-admin-connector-post",
          label: "Create Connector From Model",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-connector-by-id-manage-admin-connector-connector-id-delete",
          label: "Delete Connector By Id",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/update-connector-from-model-manage-admin-connector-connector-id-patch",
          label: "Update Connector From Model",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "chatbot-api/connector-run-once-manage-admin-connector-run-once-post",
          label: "Connector Run Once",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/gmail-auth-manage-connector-gmail-authorize-credential-id-get",
          label: "Gmail Auth",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/google-drive-auth-manage-connector-google-drive-authorize-credential-id-get",
          label: "Google Drive Auth",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/gmail-callback-manage-connector-gmail-callback-get",
          label: "Gmail Callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/google-drive-callback-manage-connector-google-drive-callback-get",
          label: "Google Drive Callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-connectors-manage-connector-get",
          label: "Get Connectors",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-connector-by-id-manage-connector-connector-id-get",
          label: "Get Connector By Id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-basic-connector-indexing-status-manage-indexing-status-get",
          label: "Get Basic Connector Indexing Status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/list-credentials-admin-manage-admin-credential-get",
          label: "List Credentials Admin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-credential-by-id-admin-manage-admin-credential-credential-id-delete",
          label: "Delete Credential By Id Admin",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/list-credentials-manage-credential-get",
          label: "List Credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/create-credential-from-model-manage-credential-post",
          label: "Create Credential From Model",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/get-credential-by-id-manage-credential-credential-id-get",
          label: "Get Credential By Id",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-credential-by-id-manage-credential-credential-id-delete",
          label: "Delete Credential By Id",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/update-credential-from-model-manage-credential-credential-id-patch",
          label: "Update Credential From Model",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "chatbot-api/get-cc-pair-full-info-manage-admin-cc-pair-cc-pair-id-get",
          label: "Get Cc Pair Full Info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/associate-credential-to-connector-manage-connector-connector-id-credential-credential-id-put",
          label: "Associate Credential To Connector",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "chatbot-api/dissociate-credential-from-connector-manage-connector-connector-id-credential-credential-id-delete",
          label: "Dissociate Credential From Connector",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/create-document-set-manage-admin-document-set-post",
          label: "Create Document Set",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/patch-document-set-manage-admin-document-set-patch",
          label: "Patch Document Set",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-document-set-manage-admin-document-set-document-set-id-delete",
          label: "Delete Document Set",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/list-document-sets-manage-document-set-get",
          label: "List Document Sets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/document-set-public-manage-document-set-public-get",
          label: "Document Set Public",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/set-new-embedding-model-secondary-index-set-new-embedding-model-post",
          label: "Set New Embedding Model",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/cancel-new-embedding-secondary-index-cancel-new-embedding-post",
          label: "Cancel New Embedding",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/get-current-embedding-model-secondary-index-get-current-embedding-model-get",
          label: "Get Current Embedding Model",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-secondary-embedding-model-secondary-index-get-secondary-embedding-model-get",
          label: "Get Secondary Embedding Model",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-embedding-models-secondary-index-get-embedding-models-get",
          label: "Get Embedding Models",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/list-slack-bot-configs-manage-admin-slack-bot-config-get",
          label: "List Slack Bot Configs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/create-slack-bot-config-manage-admin-slack-bot-config-post",
          label: "Create Slack Bot Config",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-slack-bot-config-manage-admin-slack-bot-config-slack-bot-config-id-delete",
          label: "Delete Slack Bot Config",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/patch-slack-bot-config-manage-admin-slack-bot-config-slack-bot-config-id-patch",
          label: "Patch Slack Bot Config",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "chatbot-api/get-tokens-manage-admin-slack-bot-tokens-get",
          label: "Get Tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/put-tokens-manage-admin-slack-bot-tokens-put",
          label: "Put Tokens",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "chatbot-api/list-personas-persona-get",
          label: "List Personas",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-persona-persona-persona-id-get",
          label: "Get Persona",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/build-final-template-prompt-persona-utils-prompt-explorer-get",
          label: "Build Final Template Prompt",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/create-persona-admin-persona-post",
          label: "Create Persona",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-persona-admin-persona-persona-id-delete",
          label: "Delete Persona",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/update-persona-admin-persona-persona-id-patch",
          label: "Update Persona",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "chatbot-api/patch-persona-visibility-admin-persona-persona-id-visible-patch",
          label: "Patch Persona Visibility",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "chatbot-api/patch-persona-display-priority-admin-persona-display-priority-put",
          label: "Patch Persona Display Priority",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "chatbot-api/list-available-model-versions-admin-persona-utils-list-available-models-get",
          label: "List Available Model Versions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-default-model-admin-persona-utils-default-model-get",
          label: "Get Default Model",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/list-prompts-prompt-get",
          label: "List Prompts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/create-prompt-prompt-post",
          label: "Create Prompt",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/get-prompt-prompt-prompt-id-get",
          label: "Get Prompt",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-prompt-prompt-prompt-id-delete",
          label: "Delete Prompt",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/update-prompt-prompt-prompt-id-patch",
          label: "Update Prompt",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "chatbot-api/healthcheck-health-get",
          label: "Healthcheck",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-auth-type-auth-type-get",
          label: "Get Auth Type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-version-version-get",
          label: "Get Version",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/document-ingestion-danswer-api-doc-ingestion-post",
          label: "Document Ingestion",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/gpt-search-gpts-gpt-document-search-post",
          label: "Gpt Search",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/list-user-groups-manage-admin-user-group-get",
          label: "List User Groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/create-user-group-manage-admin-user-group-post",
          label: "Create User Group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-user-group-manage-admin-user-group-user-group-id-delete",
          label: "Delete User Group",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/patch-user-group-manage-admin-user-group-user-group-id-patch",
          label: "Patch User Group",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "chatbot-api/get-query-analytics-analytics-admin-query-get",
          label: "Get Query Analytics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-user-analytics-analytics-admin-user-get",
          label: "Get User Analytics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-chat-session-history-admin-chat-session-history-get",
          label: "Get Chat Session History",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-chat-session-admin-admin-chat-session-history-chat-session-id-get",
          label: "Get Chat Session Admin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/get-query-history-as-csv-admin-query-history-csv-get",
          label: "Get Query History As Csv",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/list-api-keys-admin-api-key-get",
          label: "List Api Keys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "chatbot-api/create-api-key-admin-api-key-post",
          label: "Create Api Key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/delete-api-key-admin-api-key-api-key-id-delete",
          label: "Delete Api Key",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "chatbot-api/regenerate-existing-api-key-admin-api-key-api-key-id-patch",
          label: "Regenerate Existing Api Key",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "chatbot-api/handle-search-request-query-document-search-post",
          label: "Handle Search Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/get-answer-with-quote-query-answer-with-quote-post",
          label: "Get Answer With Quote",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "chatbot-api/handle-simplified-chat-message-chat-send-message-simple-api-post",
          label: "Handle Simplified Chat Message",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
