services:
  # postgres:
  #   image: postgres:15.2-alpine
  #   container_name: postgres
  #   hostname: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #   env_file:
  #     - .env
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   networks:
  #     - backend

  api_server:
    build:
      context: ../../chatbot-core/backend/
      dockerfile: Dockerfile
    container_name: api_server
    hostname: api_server
    command:
      ["uv", "run", "fastapi", "dev", "--host", "0.0.0.0", "--port", "5000"]
    ports:
      - "5000:5000"
    env_file:
      - ../../chatbot-core/.env
    volumes: # INFO: Mount for auto-reload code changes
      - ../../chatbot-core/backend/app:/app/app
      - ../../chatbot-core/backend/tests:/app/tests
    networks:
      - backend

# volumes:
# postgres-data:

networks:
  backend:
    driver: bridge
