/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "EzHR Chatbot Local Development Guide",
  "tagline": "EzHR Chatbot Documentation",
  "url": "https://ezhrchatbot.pages.dev",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "staticDirectories": [
    "static"
  ],
  "organizationName": "TinhHoaSolutions-EzHR",
  "projectName": "chatbot",
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/nho/Documents/ezhr/chatbot/sidebars.ts",
          "editUrl": "https://github.com/TinhHoaSolutions-EzHR/chatbot/tree/main/docs",
          "docItemComponent": "@theme/ApiItem",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ]
        },
        "blog": {
          "showReadingTime": true,
          "feedOptions": {
            "type": "all",
            "copyright": "Copyright © 2024 Facebook, Inc."
          },
          "onInlineAuthors": "ignore",
          "onUntruncatedBlogPosts": "ignore",
          "rehypePlugins": [
            null
          ],
          "remarkPlugins": [
            null
          ]
        },
        "theme": {
          "customCss": "/home/nho/Documents/ezhr/chatbot/src/css/custom.css"
        }
      }
    ]
  ],
  "stylesheets": [
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM",
      "crossorigin": "anonymous"
    }
  ],
  "themeConfig": {
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "title": "EzHR Chatbot",
      "logo": {
        "alt": "EzHR Chatbot Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "doc",
          "docId": "intro",
          "position": "left",
          "label": "Local Development Guide"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "label": "Chatbot API",
          "position": "left",
          "to": "/docs/chatbot-api/sample-backend"
        },
        {
          "href": "https://github.com/TinhHoaSolutions-EzHR/chatbot",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Local Development Guide",
              "to": "/docs/intro"
            },
            {
              "label": "Chatbot API",
              "to": "/docs/chatbot-api/sample-backend"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/TinhHoaSolutions-EzHR/chatbot"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2024 EzHR Chatbot."
    },
    "prism": {
      "prism": {
        "additionalLanguages": [
          "ruby",
          "csharp",
          "php",
          "java",
          "powershell",
          "json",
          "bash"
        ]
      },
      "languageTabs": [
        {
          "highlight": "python",
          "language": "python",
          "logoClass": "python"
        },
        {
          "highlight": "bash",
          "language": "curl",
          "logoClass": "bash"
        },
        {
          "highlight": "csharp",
          "language": "csharp",
          "logoClass": "csharp"
        },
        {
          "highlight": "go",
          "language": "go",
          "logoClass": "go"
        },
        {
          "highlight": "javascript",
          "language": "nodejs",
          "logoClass": "nodejs"
        },
        {
          "highlight": "ruby",
          "language": "ruby",
          "logoClass": "ruby"
        },
        {
          "highlight": "php",
          "language": "php",
          "logoClass": "php"
        },
        {
          "highlight": "java",
          "language": "java",
          "logoClass": "java",
          "variant": "unirest"
        },
        {
          "highlight": "powershell",
          "language": "powershell",
          "logoClass": "powershell"
        }
      ],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "plugins": [
    [
      "docusaurus-plugin-openapi-docs",
      {
        "id": "openapi",
        "docsPluginId": "classic",
        "config": {
          "chatbotApi": {
            "specPath": "static/openapi.yaml",
            "outputDir": "docs/chatbot-api",
            "sidebarOptions": {
              "groupPathsBy": "tag",
              "categoryLinkSource": "tag"
            }
          }
        }
      }
    ]
  ],
  "themes": [
    "docusaurus-theme-openapi-docs"
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
