name: "Auto Assign"
on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    name: Auto
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: "Auto assign for pull request"
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: ".github/assign.yml"
