name: "PR Labeler"
on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  labeler:
    name: auto label
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@v5
