name: Deploy to dbdocs.io

on:
  push:
    paths:
      - "chatbot-core/EzHR-Chatbot.dbml"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dbdocs
        run: sudo npm install -g dbdocs

      - name: Check dbdocs
        run: dbdocs

      - name: Update dbdocs project
        env:
          DBDOCS_TOKEN: ${{ secrets.dbdocs_token.DBDOCS_TOKEN }}
        run: dbdocs build chatbot-core/EzHR-Chatbot.dbml
