name: Lint

# Runs on every commit in pull request to main
# Path including all .py files
on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.py"

jobs:
  lint-python:
    name: lint python files
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out ${{ github.head_ref }}
        uses: actions/checkout@v4

      # INFO: Use uv as a python installation & dependency manager
      # https://docs.astral.sh/uv/guides/integration/github/
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.20"
          enable-cache: true

      # Get changes python files and save to github env
      - name: Get changed python files
        id: get_changed_files
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD | tr -s ' ' '\n' | grep -E '.*[.]py$' | tr -s '\n' ' ') || true
          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No python files changed."
            CHANGED_FILES=""
          fi
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "Linting $CHANGED_FILES"

      # INFO: ruff version 0.9.5 is matched with pyproject.toml
      - name: Lint python files
        if: env.CHANGED_FILES != ''
        run: |
          uvx ruff@0.9.5 check --output-format=github ${{ env.CHANGED_FILES }} || true
