name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release"
        type: boolean
        required: false
        default: true
  # Schedule every 2 weeks
  schedule:
    - cron: "0 0 */14 * *"
  # Pull request name contains "release-please"
  push:
    branches:
      - main
    paths:
      - ".github/release-please-manifest.json"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    if: ${{ inputs.release && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Config release-please
        id: config-release-please
        run: |
          if [ -f .github/release-please-config.json ]; then
            echo "config-file=.github/release-please-config.json" >> $GITHUB_OUTPUT
            [ -f .github/release-please-manifest.json ] &&
              echo "manifest-file=.github/release-please-manifest.json" >> $GITHUB_OUTPUT
          else
            echo "release-type=simple" >> $GITHUB_OUTPUT
          fi
          exit 0

      - name: Release
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          config-file: ${{ steps.config-release-please.outputs.config-file }}
          manifest-file: ${{ steps.config-release-please.outputs.manifest-file }}
          release-type: ${{ steps.config-release-please.outputs.release-type }}
          include-component-in-tag: true

      - name: Tag stable versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name ubunchuu-admin[bot]
          git config user.email 159746302+ubunchuu-admin@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.CI_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d v${{ steps.release.outputs.major }} || true
          git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git push origin :v${{ steps.release.outputs.major }} || true
          git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git tag -a v${{ steps.release.outputs.major }} -m "chore(release): release v${{ steps.release.outputs.major }}"
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "chore(release): release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
          git push origin v${{ steps.release.outputs.major }}
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
